import { Candidate } from "@/types/ats";

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "c1",
    name: "Murad Əliyev",
    email: "murad@example.com",
    location: "Bakı, Azərbaycan",
    currentRole: "Senior Frontend Developer",
    experienceYears: 6,
    skills: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    education: ["Bakı Dövlət Universiteti - Kompüter Elmləri"],
    matchingScore: 92,
    analysisStatus: "completed",
    appliedAt: "2024-03-10T10:00:00Z",
    status: "Interview",
    appliedJobTitle: "Senior React Developer",
  },
  {
    id: "c2",
    name: "Aysel Məmmədova",
    email: "aysel@example.com",
    location: "Sumqayıt, Azərbaycan",
    currentRole: "UI/UX Designer",
    experienceYears: 3,
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    education: ["ADNSU - Dizayn"],
    matchingScore: 85,
    analysisStatus: "completed",
    appliedAt: "2024-03-11T14:30:00Z",
    status: "Screening",
    appliedJobTitle: "Product Designer",
  },
  {
    id: "c3",
    name: "Kənan Həsənov",
    email: "kenan@example.com",
    location: "Gəncə, Azərbaycan",
    currentRole: "Backend Developer",
    experienceYears: 4,
    skills: ["Node.js", "PostgreSQL", "Docker", "Redis"],
    education: ["BANM - Proseslərin Avtomatlaşdırılması"],
    matchingScore: 78,
    analysisStatus: "completed",
    appliedAt: "2024-03-12T09:15:00Z",
    status: "Applied",
    appliedJobTitle: "Backend Engineer",
  },
  {
    id: "c4",
    name: "Leyla Rzayeva",
    email: "leyla@example.com",
    location: "Bakı, Azərbaycan",
    currentRole: "Junior Frontend Developer",
    experienceYears: 1,
    skills: ["HTML", "CSS", "JavaScript"],
    education: ["Code Academy - Frontend Bootcamp"],
    matchingScore: 45,
    analysisStatus: "completed",
    appliedAt: "2024-03-12T16:45:00Z",
    status: "Rejected",
    appliedJobTitle: "Senior React Developer",
  },
];
