import { Job } from "@/types/job";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Front End Engineer, DynamoDB",
    company: "Amazon",
    companyLogo: "/images/logos/amazon.png",
    location: "Dublin, CA",
    locationType: "in-office",
    city: "Dublin",
    state: "CA",
    jobType: "full-time",
    experienceLevel: "junior",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    featured: true,
    isNew: true,
  },
  {
    id: "2",
    title: "UX Engineer, Android XR",
    company: "Google",
    companyLogo: "/images/logos/google.png",
    location: "New York, NY",
    locationType: "remote",
    city: "New York",
    state: "NY",
    jobType: "full-time",
    experienceLevel: "mid",
    salary: "$225 / hr",
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    featured: true,
    isNew: false,
  },
  {
    id: "3",
    title: "Software Engineer III, Full Stack, Chrome",
    company: "Google",
    companyLogo: "/images/logos/google.png",
    location: "Mountain View, CA",
    locationType: "in-office",
    city: "Mountain View",
    state: "CA",
    jobType: "full-time",
    experienceLevel: "mid",
    salary: "$150,000",
    postedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
    isNew: false,
  },
  {
    id: "4",
    title: "Staff Software Engineer, Front End, Gemini Cloud Assist",
    company: "Google",
    companyLogo: "/images/logos/google.png",
    location: "San Francisco, CA",
    locationType: "hybrid",
    city: "San Francisco",
    state: "CA",
    jobType: "full-time",
    experienceLevel: "senior",
    salary: "$225,000",
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
    isNew: false,
  },
  {
    id: "5",
    title: "Senior React Developer",
    company: "Meta",
    companyLogo: "/images/logos/meta.png",
    location: "Menlo Park, CA",
    locationType: "hybrid",
    city: "Menlo Park",
    state: "CA",
    jobType: "full-time",
    experienceLevel: "senior",
    salary: "$180,000",
    postedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
    isNew: false,
  },
  {
    id: "6",
    title: "Frontend Engineer, Design Systems",
    company: "Figma",
    companyLogo: "/images/logos/figma.png",
    location: "Remote",
    locationType: "remote",
    city: "",
    state: "any",
    jobType: "full-time",
    experienceLevel: "mid",
    salary: "$160,000",
    postedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    featured: false,
    isNew: true,
  },
  {
    id: "7",
    title: "Junior Frontend Developer",
    company: "Stripe",
    companyLogo: "/images/logos/stripe.png",
    location: "Seattle, WA",
    locationType: "in-office",
    city: "Seattle",
    state: "WA",
    jobType: "full-time",
    experienceLevel: "junior",
    salary: "$120,000",
    postedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    featured: false,
    isNew: false,
  },
];

